### ISSUE TITLE
SANS SEC 573: Step 3 of Lab 2.1.0; "ERROR: Could not build wheels for pywars, which is required to install pyproject.toml-based projects"

### ISSUE THREAD

**Issue by maferna** [MarkBaggett/pyWars#4]
student@SEC573:~/Desktop/lab2.1.0$ pip install git+https://github.com/markbaggett/pywars@version5
Defaulting to user installation because normal site-packages is not writeable
Collecting git+https://github.com/markbaggett/pywars@version5
  Cloning https://github.com/markbaggett/pywars (to revision version5) to /tmp/pip-req-build-bwl6lctm
  Running command git clone --filter=blob:none --quiet https://github.com/markbaggett/pywars /tmp/pip-req-build-bwl6lctm
  Running command git checkout -b version5 --track origin/version5
  Switched to a new branch 'version5'
  Branch 'version5' set up to track remote branch 'version5' from 'origin'.
  Resolved https://github.com/markbaggett/pywars to commit 046bc33bbde1dc56404ceb484f70575c5298297e
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting rich>=9.1.0
  Using cached rich-13.7.0-py3-none-any.whl (240 kB)
Requirement already satisfied: requests>=2.20.0 in /usr/lib/python3/dist-packages (from pywars==5.0.3) (2.25.1)
Collecting markdown-it-py>=2.2.0
  Using cached markdown_it_py-3.0.0-py3-none-any.whl (87 kB)
Collecting pygments<3.0.0,>=2.13.0
  Using cached pygments-2.17.2-py3-none-any.whl (1.2 MB)
Collecting mdurl~=0.1
  Using cached mdurl-0.1.2-py3-none-any.whl (10.0 kB)
Building wheels for collected packages: pywars
  Building wheel for pywars (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building wheel for pywars (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [61 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib
      creating build/lib/pywars
      copying pywars/__init__.py -> build/lib/pywars
      copying pywars/__main__.py -> build/lib/pywars
      copying pywars/client.py -> build/lib/pywars
      running install
      running install_lib
      Traceback (most recent call last):
        File "/usr/lib/python3/dist-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
          main()
        File "/usr/lib/python3/dist-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/usr/lib/python3/dist-packages/pip/_vendor/pep517/in_process/_in_process.py", line 261, in build_wheel
          return _build_backend().build_wheel(wheel_directory, config_settings,
        File "/usr/lib/python3/dist-packages/setuptools/build_meta.py", line 230, in build_wheel
          return self._build_with_temp_dir(['bdist_wheel'], '.whl',
        File "/usr/lib/python3/dist-packages/setuptools/build_meta.py", line 215, in _build_with_temp_dir
          self.run_setup()
        File "/usr/lib/python3/dist-packages/setuptools/build_meta.py", line 267, in run_setup
          super(_BuildMetaLegacyBackend,
        File "/usr/lib/python3/dist-packages/setuptools/build_meta.py", line 158, in run_setup
          exec(compile(code, __file__, 'exec'), locals())
        File "setup.py", line 3, in <module>
          setuptools.setup(
        File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 153, in setup
          return distutils.core.setup(**attrs)
        File "/usr/lib/python3/dist-packages/setuptools/_distutils/core.py", line 148, in setup
          return run_commands(dist)
        File "/usr/lib/python3/dist-packages/setuptools/_distutils/core.py", line 163, in run_commands
          dist.run_commands()
        File "/usr/lib/python3/dist-packages/setuptools/_distutils/dist.py", line 967, in run_commands
          self.run_command(cmd)
        File "/usr/lib/python3/dist-packages/setuptools/_distutils/dist.py", line 986, in run_command
          cmd_obj.run()
        File "/usr/lib/python3/dist-packages/wheel/bdist_wheel.py", line 335, in run
          self.run_command('install')
        File "/usr/lib/python3/dist-packages/setuptools/_distutils/cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "/usr/lib/python3/dist-packages/setuptools/_distutils/dist.py", line 986, in run_command
          cmd_obj.run()
        File "/usr/lib/python3/dist-packages/setuptools/command/install.py", line 68, in run
          return orig.install.run(self)
        File "/usr/lib/python3/dist-packages/setuptools/_distutils/command/install.py", line 622, in run
          self.run_command(cmd_name)
        File "/usr/lib/python3/dist-packages/setuptools/_distutils/cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "/usr/lib/python3/dist-packages/setuptools/_distutils/dist.py", line 985, in run_command
          cmd_obj.ensure_finalized()
        File "/usr/lib/python3/dist-packages/setuptools/_distutils/cmd.py", line 107, in ensure_finalized
          self.finalize_options()
        File "/usr/lib/python3/dist-packages/setuptools/command/install_lib.py", line 17, in finalize_options
          self.set_undefined_options('install',('install_layout','install_layout'))
        File "/usr/lib/python3/dist-packages/setuptools/_distutils/cmd.py", line 290, in set_undefined_options
          setattr(self, dst_option, getattr(src_cmd_obj, src_option))
        File "/usr/lib/python3/dist-packages/setuptools/_distutils/cmd.py", line 103, in __getattr__
          raise AttributeError(attr)
      AttributeError: install_layout. Did you mean: 'install_platlib'?
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pywars
Failed to build pywars
ERROR: Could not build wheels for pywars, which is required to install pyproject.toml-based projects
![Screenshot 2024-02-24 at 6 11 01 PM](https://github.com/MarkBaggett/pyWars/assets/17960136/5c2d64b1-d1a9-4a13-b4d7-d78bf53b001a)
![Screenshot 2024-02-24 at 6 12 11 PM](https://github.com/MarkBaggett/pyWars/assets/17960136/f4ea3f70-abee-4f52-a09d-b949a87f3fe5)
![Screenshot 2024-02-24 at 6 12 34 PM](https://github.com/MarkBaggett/pyWars/assets/17960136/4777814c-e831-4422-b91c-34e146ae73b4)

**Comment by maferna** [comment]
Found the issue.  1) Run from the right shell environment; 2) Generate a git Personal Access Token as you can no longer authenticate to GitHub with username/pw.
